### ISSUE TITLE
Rank Commands Do Not Work

### ISSUE THREAD

**Issue by sauceadmiral** [MC-Prison/Prison#10]
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for?

Core/Ranks

### Describe the issue you are experiencing.

Whenever I use a rank-related command (/pranks, /rankup, etc.) It gives the message "Ranks are disabled." In my configuration file, ranks are set to true. Problem?

### Describe the steps to reproduce the problem.

Using Prison version 2.2.3 downloaded from Bukkit, running on Spigot 1.10.2 server.
Happens with any rank commands, everything else works fine.

### Anything else we need to know?

Nope

**Comment by SirFaizdat** [comment]
Sorry, but you've submitted this issue in the wrong repository. This is the repository for Prison v3.0, an upcoming release and successor to Prison v2.x (which you are using). The repository that this issue belongs in is [SirFaizdat/Prison](https://github.com/SirFaizdat/Prison/issues).
