### ISSUE TITLE
Scoreboard module

### ISSUE THREAD

**Issue by DylanFPS** [MC-Prison/Prison#11]
Having a Prison Team endorsed scoreboard plugin allows us to provide support for those issues with scoreboards. It also allows us to better interact with the other Prison modules and spare third-party developers the integration of Prison 3.

This will not be present in the Initial release. And don't worry, I'll do this one :)

**Comment by SirFaizdat** [comment]
Good idea! A scoreboard API needs to be added to Prison-Core though, perhaps that can be planned for API 31.

**Comment by SirFaizdat** [comment]
A scoreboard API has been created. [Documentation can be found here](https://github.com/MC-Prison/Prison/wiki/Scoreboard-API).

**Comment by faizaand** [comment]
Perhaps it would be better to implement Prison 3 into other scoreboards instead of creating our own, because that way, server owners can use a whole menagerie of variables in their scoreboards.
