### ISSUE TITLE
Mines release candidate summary

### ISSUE THREAD

**Issue by DMP9-MC** [MC-Prison/Prison#17]
Here lies a (growing) list of things that need to be done to mines by the initial release. Items may be added when problems arise.

- [x] Fix player still gets block drops even when in creative ~~[requires API changes]~~
- [x] Fix player can get stuck in mine
- [x] Add message customization
- [x] Fix cache doesn't clear when a mine block list is modified (using async reset) 
- [x] Delete old mine files
- [x] Fix GUI doesn't react to clicks [can't reproduce]

Assigned testers for mines: @AzyIsCool @TotallyALF5

**Comment by AzyIsCool** [comment]
On the [**Mines: The basics**](https://github.com/MC-Prison/Prison/wiki/Mines:-The-basics#delete-a-mine) page, the Delete a mine bit is wrong.

Says:

If you don't want your mine anymore, simply delete it using:

` /mines spawnpoint <mineName> `


Should Be

If you don't want your mine anymore, simply delete it using:

` /mines delete <mineName>`

**Comment by DMP9-MC** [comment]
@AzyIsCool Good catch! Will change this now, thanks! :)

**Comment by DMP9-MC** [comment]
Closing until bugs pop up in release candidate 2

**Comment by AzyIsCool** [comment]
Got a bug

When you create a mine then stop the server, you not be able to delete the mine by the delete command when you start the server again  (you have to delete the .json file that it makes for that mine)

So you can only delete the mine if the server hasn't been stopped when it was created

**Comment by DMP9-MC** [comment]
@AzyIsCool added to TO-DO list

**Comment by DMP9-MC** [comment]
@AzyIsCool Bug fixed, will be in RC3 (if any) and definitely in the full release.

**Comment by AzyIsCool** [comment]
Spawnpoint is not working at all.

[Link to show it not working](https://www.youtube.com/watch?v=A_WI0tPRUR8&feature=youtu.be)

**Comment by DMP9-MC** [comment]
@AzyIsCool Interesting... Can you send me your server (via GitHub comments) so I can attempt to reproduce the problem?

**Comment by AzyIsCool** [comment]
I can`t because of the size but I put it on my website: [(Link)](http://aarongaming.webege.com/Minecraft_Server.7z)
