### ISSUE TITLE
Mines Module not loading - Latest build until now

### ISSUE THREAD

**Issue by Lmmb74** [MC-Prison/Prison#2]
### Which of the following are you submitting this issue for?
- [ ] Prison Core
- [X] Prison Mines
- [ ] Prison Ranks
- [ ] Prison Cells
- [ ] Prison Shops

### Describe the issue you are experiencing.

When I start the server, the console does not print out that the module was loaded. And when I checked if it was not loaded with the cmd /prison modules, I did not find it loaded.
I tested it on Spigot 1.9.4 latest build & Spigot 1.8.9 latest build.

**Comment by SirFaizdat** [comment]
Do the other modules load?

**Comment by Lmmb74** [comment]
Yes

**Comment by SirFaizdat** [comment]
I just realized you were referring to mines. The mines module is not yet complete.

**Comment by Lmmb74** [comment]
Ok thanks
