### ISSUE TITLE
Help On The Latest Version Of Prison PLugin It Doesnt Allow Me To do /prisonranks add A 0 It says Ranks Are Disabled!

### ISSUE THREAD

**Issue by Bossosking** [MC-Prison/Prison#24]
EveryTime IT DOES THIS EVEN WHEN I REDOWNLOAD HELP PLZ! I Cant Find A Better PLugin Than This!

**Comment by DylanFPS** [comment]
Do you have a permissions plugin setup?

**Comment by DylanFPS** [comment]
Just realized this is about Prison 2 and this is the Prison 3 repository. Please report bugs to the [Prison 2 bug report page](https://github.com/SirFaizdat/Prison/issues/)
