### ISSUE TITLE
Website link DEAD...

### ISSUE THREAD

**Issue by maxlehot1234** [MC-Prison/Prison#29]
Hi just to told you that your website was dead.
https://mc-prison.tech/beta-builds/

Any way to put releases on github? Or a new link?

Thank you so much ;)

**Comment by Camouflage100** [comment]
No new link; I'll look into this.

**Comment by faizaand** [comment]
For now, you can just use our [releases page](https://github.com/MC-Prison/Prison/releases/tag/v0.10.0) :) Thank you for your interest, we'll have the site fixed soon!

**Comment by faizaand** [comment]
The new website is https://faizaand.me/prison. It's still a work in progress, but that's gonna be its home!

**Comment by maxlehot1234** [comment]
Nice, but the download (release page) show only prison-api.jar. Is it normal?

**Comment by faizaand** [comment]
Nope, let me upload the Spigot JAR. Good catch!

**Comment by faizaand** [comment]
There we go, uploaded.

**Comment by maxlehot1234** [comment]
Thanks a lot I will test it asap ;)

**Comment by faizaand** [comment]
You'll probably want these too!

https://github.com/MC-Prison/PrisonMines/releases
https://github.com/MC-Prison/PrisonRanks/releases

Thanks :)

**Comment by maxlehot1234** [comment]
Thanks and for mines, they can be in ANY shape? and support 1.12 blocks?

**Comment by faizaand** [comment]
@maxlehot1234 They can be in any cuboid shape, and they do support 1.12 blocks.

**Comment by faizaand** [comment]
**Note** I just re-uploaded the JAR right now because I noticed an error and fixed it. If you downloaded it already, you'll have to re-download it.
