### ISSUE TITLE
Autosmelt never turns off

### ISSUE THREAD

**Issue by faizaand** [MC-Prison/Prison#32]
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for?
Mines

### Describe the issue you are experiencing.
Autosmelt never turns off.

### Describe the steps to reproduce the problem.
1. Type /autosmelt.
1. Mine some stuff.
1. Type /autosmelt again. It should say it's been disabled.
1. Mine some more stuff. It still auto smelts!

**Comment by faizaand** [comment]
Fixed by removing autosmelt! It's not even a mines core feature anyway.

**Comment by DylanFPS** [comment]
This is a really lazy solution to this problem!

**Comment by faizaand** [comment]
@DylanFPS Well, auto-smelt and auto-block go against the module system anyways, since it's not technically a core mines feature.

**Comment by DylanFPS** [comment]
True, but autosmelt has been there for ages and I use it as a perk for
donors on my servers

**Comment by faizaand** [comment]
https://dev.bukkit.org/projects/autosmelt
