### ISSUE TITLE
Rank setup

### ISSUE THREAD

**Issue by JustinSaenCity** [MC-Prison/Prison#35]
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for?

Ranks

### Describe the issue you are experiencing.
I try adding ranks to rankup in prison, i created all ranks, iheritted them all and even put them in a track. but when i type /rankup i got rank upped by the prison plugin, but in the perm plugin (i am using luckperms) i keep the rank i first had, how do i make it so when i rankup in the prison plugin i do with my perm plugin too?
### Describe the steps to reproduce the problem.
I have the version of the site (i tought that was version 3) i made all ranks and iheritted them and i made ranks a-d in the prison plugin, when i type /rankup i get rank upped in the prison plugin, but not with my perm plugin, how do i set it up so it will work?

### Anything else we need to know?

I use luckperms and vault so i tought that would connect it!

**Comment by faizaand** [comment]
Prison 3's new system uses something called Rank commands to connect to your permission plugin. This eliminates the Prison 2 infinite rankup bug and gives you more control.

Try /rank command add <yourRank> /lp user {player} add <group>

Sorry, I don't know the Luckperms group command. {player} is replaced by the player's name. 

_Sent from my Samsung SM-G950U using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by JustinSaenCity** [comment]
Ow, tysm I tried %player%, %player_name% and even @p but it didn't work, maybe add that on the main page of the site, it will help a lot of ppl out I think, because in a discord help chat some1 even got into the source code and couldn't find anything. But thanks for the fast reply :)

**Comment by faizaand** [comment]
Yeah, we're still working on the docs for Prison 3 as it's in beta. Thanks for pointing that out :)
