### ISSUE TITLE
/prison sync

### ISSUE THREAD

**Issue by JustinSaenCity** [MC-Prison/Prison#36]
Hi,
I have to restart my server again and again when i change the config, can you add a /prison reload command so it will be easier to reload all the configs?
thanks in advance,
Justin

**Comment by faizaand** [comment]
@JustinSaenCity Can't believe I forgot that! I will look into adding it for v1.1, since v1.0 has already been finalized.

**Comment by faizaand** [comment]
Instead of having a reload command, we've decided that we're going to make a new configuration system that watches for file changes and silently reloads itself so you don't have to! Neat, eh? This is the new issue, I'm closing this one in favor of that one: #53
