### ISSUE TITLE
An idea for Prison tags

### ISSUE THREAD

**Issue by TheGamingCats** [MC-Prison/Prison#39]
### Which module are you submitting this issue for?
Ranks, Spigot
Example: Core, Mines, Ranks, Shops, Cells, Gangs, Spigot, Sponge, etc.

### My idea:
Basically, I want a way to make it so that you can set the tags to only be visible in some worlds. I do not want these roles, for example, appearing in other minigames.

**Comment by faizaand** [comment]
This is a great idea!

**Comment by faizaand** [comment]
This issue is better described in #48 so I'm going to close this one.
