### ISSUE TITLE
No Ranks Command! (Prison 3)

### ISSUE THREAD

**Issue by Nikko019** [MC-Prison/Prison#40]
**Which module are you submitting this issue for?**
    -Ranks

**Describe the issue you are experiencing.**
     When I want to try and edit the "Ranks," no commands show up other than the ranks 
     spamming my chat. I checked if there was a config file for the ranks, but there was not any. I 
     tried /ranks set, /ranks create, and once typed and entered, the ranks list pops up. What do I do?

**Anything else we need to know?**
   -Other than that, I really enjoy the plugin!

**Comment by SevenSlayy** [comment]
try /pranks create

**Comment by faizaand** [comment]
You need to have the **ranks.admin** permission in order to access those commands (like /ranks set, /ranks create, etc). Otherwise, it just shows the rank list like it does to normal users.

Documentation for the project is coming soon, so this won't be a point of confusion after that.
