### ISSUE TITLE
/Sell

### ISSUE THREAD

**Issue by Sallomy** [MC-Prison/Prison#41]
While I was settings up I tried to break then I said /Sell all it sold the diamond pick axe..... you should make it never sell an item it should only sell blocks

**Comment by SevenSlayy** [comment]
I don't think Prison handles /sell does it?

**Comment by Sallomy** [comment]
Maybe essentials plugin?

**Comment by MegaJoshy** [comment]
If you have essentials it will most likely be that. if you would like to edit what gets sole it's in the essentials folder.

**Comment by MCTyler** [comment]
Try this for selling ores....https://www.spigotmc.org/resources/autosell.2157/

**Comment by faizaand** [comment]
As of now, Prison does not handle the `/sell` command ([though it plans to in the future!](https://github.com/MC-Prison/Prison/issues/9)). You'll have to use another system for now, such as Essentials or AutoSell.
