### ISSUE TITLE
Default rank Issue

### ISSUE THREAD

**Issue by Bobcatsss** [MC-Prison/Prison#63]
Ranks

Issue: I created 3 ranks on the default ladder A, B and C with A having a cost of $0 yet every new players rank is set to B. B's cost is $75,000 Note: A was the first rank i created

How to re-create: Simply create 2 ranks with the first one you create having a cost of $0 and new players will get the second rank not the first one.

**Comment by DylanFPS** [comment]
Hmmm interesting. Can you send me your rank files please?

**Comment by Bobcatsss** [comment]
[ranks.zip](https://github.com/MC-Prison/Prison/files/1669842/ranks.zip)

**Comment by DylanFPS** [comment]
Fixed as of [`3be4507`](https://github.com/MC-Prison/Prison/commit/3be45075246b8bbcb4e5e9168ce7363e44011336), will try to pass this as an emergency patch when the rest of the team is online.

**Comment by faizaand** [comment]
@Bobcatsss @DylanFPS Prison v3.0.2 (hopefully) fixed this problem. You can download it from Bukkit, Spigot, or [here](https://github.com/MC-Prison/Prison/releases/tag/3.0.2).

**Comment by Bobcatsss** [comment]
Thank you
