### ISSUE TITLE
java.lang.LinkageError when using /rankup.

### ISSUE THREAD

**Issue by botiapa** [MC-Prison/Prison#64]
### Which module are you submitting this issue for?

Ranks

### Describe the issue you are experiencing.
The plugin worked as intended, until I added commands. When someone ranks up, I add them to a group using "/manuadd {player} rank". When I use the command /rankup, I get the wanted group, but I also get a warning message(I will llink it down below.)

### Describe the steps to reproduce the problem.
Add a command to a rank, and use the command /rankup.

### Anything else we need to know?

The link for the log:  https://pastebin.com/9H31Gt7e

**Comment by DylanFPS** [comment]
This doesn't appear to be anything too bad, but thanks for pointing it out. Frankly I have no idea what this is, maybe you forgot to give Java a cookie?

PS: We recommend you use Spigot. If you are using Bukkit, why?

**Comment by faizaand** [comment]
The error you're seeing is due to Java finding that there are two class loaders loading the same class. So far, I've been unsuccessful in recreating the problem.

Is there unique about about your server setup?

**Comment by botiapa** [comment]
I'm using spigot.

**Comment by botiapa** [comment]
It seems like I solved this. I was using a plugin to unload and then load prison. And I think it does not like getting reloaded while the server is running.
