### ISSUE TITLE
Mines Module

### ISSUE THREAD

**Issue by SirFaizdat** [MC-Prison/Prison#7]
The Mines module's primary purpose is to add resetting mines to the game. Prison servers use mines to allow players to collect resources to either use to create more items, or to sell and rank up.

The checklist below is subject to change as feature ideas are added.
- [x] Basic mine loading and saving
- [x] Basic mine creation and in-game editing
- [x] Mine resets and reset modes
- [x] Ranks integration
- [x] Reset timer
- [x] Mine protection based on ranks

**Comment by DMP9-MC** [comment]
Some methods for ranks to use have been added - such as GUI filter overrides. Ranks should softdepend/depend on mines as what is it without it?

**Comment by SirFaizdat** [comment]
@DMP9-MC The idea of modules is that they should be able to work independently of eachother. So, mines should definitely not depend on ranks to carry out most of its features. Therefore, *softdepend*.

**Comment by DMP9-MC** [comment]
@SirFaizdat Mines doesn't depend on anything (other than Prison API of course). Mines is designed so other modules can softdepend on it. Modules can override mine teleportation, what mines are shown in the GUIs etc.

**Comment by DMP9-MC** [comment]
# Update
As of commit [e13b173](https://github.com/MC-Prison/PrisonMines/commit/e13b173085f9e5415081e5d06a963a9a2a898a34) mines is *pretty much* done

**Comment by DMP9-MC** [comment]
It loads but some things need to be done
[ ] Mines & config are never saved
[ ] Reset timer

**Comment by DMP9-MC** [comment]
I'm going to close this issue as I'm just bug fixing now. Will reopen if anything big enough pops up, otherwise follow the progress at https://github.com/mc-prison/prisonmines
