### ISSUE TITLE
Mines does not teleport you out, reset block ids does not reset

### ISSUE THREAD

**Issue by howy7214** [MC-Prison/Prison#70]
Which module are you submitting this issue for?
 Mines

Describe the issue you are experiencing.
The mines does not teleport you out when it resets, also block id 159:2 and 159:4  does not reset as will turns into White Terracotta.

Thank you for helping

Spigot 1.12.2-R0.1-SNAPSHOT     Prison v3.0.3

**Comment by DylanFPS** [comment]
Hello,

It appears as if the API is limited and cannot reset block ids like that properly. Feel free to try to use some of our 8000+ possible block names, such as `magentaclay` and see if they reset properly.

As for the teleport bug, we're aware of this and are working on a fix.

**Comment by DylanFPS** [comment]
Fixed as of [`cd70b60`](https://github.com/MC-Prison/Prison/commit/cd70b6009d926c21321a5b077b8a554fb38737d8), will be implemented in Prison 3.1
