### ISSUE TITLE
How do I run commands when users rank up, to give them access to new permissions?

### ISSUE THREAD

**Issue by finnan04** [MC-Prison/Prison#73]
How do I run commands when users rank up, to give them access to new permissions?

**Comment by DylanFPS** [comment]
Hi finnan04, thanks for using Prison! You can get a detailed tutorial on Ranks in our Ranks Guidebook! https://github.com/MC-Prison/Prison/wiki/Ranks-Guidebook In that guidebook, there is information on how to execute commands (i.e. a permission change command) when a user ranks up.

**Comment by finnan04** [comment]
Before you replied, I didn't know that the '/ranks command' command existed, so that was helpful but I am still having troubles.

When I use the commands:

_/ranks command add a essentials.warp
/ranks command add a essentials.warp a
/ranks command add b essentials.warp
/ranks command add b essentials.warp a
/ranks command add b essentials.warp b_

Rank 'a' still has permission to '/warp b'.

This is what my permissions.yml in PermissionsEx looks like:
https://pastebin.com/QsxunGdu

**Comment by DylanFPS** [comment]
You're using the command incorrectly. It should look something like this:
`/ranks command a pex user <user> add essentials.warp`
`/ranks command a pex user <user> add essentials.warp.a`

**Comment by finnan04** [comment]
That command isn't working it just tells me all the subcommands when I do it.

**Comment by DylanFPS** [comment]
Apologies, I mistyped. 
`/ranks command add a pex user <user> add essentials.warp`
`/ranks command add a pex user <user> add essentials.warp.a`

**Comment by finnan04** [comment]
This still hasn't fixed my original problem. What should my permissions.yml look like?

I can still do '/warp b' even though I'm only 'a' rank.

By the way, I am using PEX for my staff / donator ranks.

**Comment by finnan04** [comment]
Not sure if this video will explain my problem very well but I tried my best:
https://youtu.be/FHv4ZGN7vC0

**Comment by SevenSlayy** [comment]
I don't think this is a problem with Prison at all

**Comment by DylanFPS** [comment]
Yeah me neither. Check your PEX config over. I can't really suggest anything else, Prison only adds the permissions you tell it to.

**Comment by SevenSlayy** [comment]
I think the problem is you cant do the command because you hadnt ranked up, make groups A-Z and add pex user <user> group add A instead of adding them to the player and rankup

**Comment by finnan04** [comment]
This is my PEX config:
https://pastebin.com/hVZYjqcP

**Comment by DylanFPS** [comment]
As a server owner, it's your responsibility to make sure your config is correct. I don't mind helping you with the Prison config, as that's what I'm here for :)

**Comment by SevenSlayy** [comment]
Once you rankup to the rank you added the permissions to send the permissions.yml

**Comment by DylanFPS** [comment]
By the looks of things, this is completely unrelated to Prison.

**Comment by cbwolfe32** [comment]
The ticket is closed, please stop replying.
