### ISSUE TITLE
prefixes 

### ISSUE THREAD

**Issue by KalebLis2013** [MC-Prison/Prison#75]
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for? ranks

Ranks

### Describe the issue you are experiencing.
I am having trouble getting prefixes to show up in chat I have downloaded essentials chat and added it to the chat format I have created a new rank ladder and given myself the rank "a" but it will not show up in chat. I think it may be because I have other ranks setup in permission ex and I have not added it there but I am not sure.

### Describe the steps to reproduce the problem.
not sure i have messed around with it to much after it not working

### Anything else we need to know?
i prefer to be contacted through skype loopykid5762 or discord yee#0194

If there is anything else that you think will help us solve the problem, please tell us here.

**Comment by Sabermoose** [comment]
same issue

**Comment by DylanFPS** [comment]
What's your essentialschat config?

**Comment by Sabermoose** [comment]
Nvm I just decided to go with Pex and use Exchat.

I reccomend those.

**Comment by DylanFPS** [comment]
Good job sorting it out!
