### ISSUE TITLE
Reloading or restarting server causes block id to reset; Also some ids don't.

### ISSUE THREAD

**Issue by pikachu99** [MC-Prison/Prison#77]
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for?
Mines

### Describe the issue you are experiencing.
Issue1: When I restart or reload my server, the mines that have ids such as 1:1 gets removes the data or (:1). 
Issue2: When I do /mines block add Mine1 stone:1; it says stone:1 isn't a block.
### Describe the steps to reproduce the problem.
Issue1: create a mine with blocks with data such as 1:1 then restart or reload the server.
Issue2: doing /mines block add Mine1 stone:1

### Anything else we need to know?
I am using Prison 3.1

**Comment by DylanFPS** [comment]
Ah ok. Please attach your data_storage folder as a ZIP file so we can experiment on our own PCs.

**Comment by pikachu99** [comment]
[data_storage.zip](https://github.com/MC-Prison/Prison/files/1810106/data_storage.zip)

**Comment by DylanFPS** [comment]
Thanks, I'm fairly busy at the moment so I'll be sure to look into this when I have the chance :)

**Comment by pikachu99** [comment]
Ok.

**Comment by faizaand** [comment]
@pikachu99 This is actually a design decision. Mojang and Bukkit have moved away from supporting the legacy block IDs (1:1, stone:1) etc. To get what you want, you should be able to just type "granite" in the mines command. Reopen this issue if it still doesn't work.
