### ISSUE TITLE
/ranks issue

### ISSUE THREAD

**Issue by Hxtch2** [MC-Prison/Prison#80]
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for?

Ranks

### Describe the issue you are experiencing.
So after setting up the ranks ingame, I restarted the server. After restarting the server errors put up in console only on the ranks being loaded the mines are fine and going back on, when i do /ranks it says unknown command its like when i restart the server /ranks just disappear. When i do /prison modules it still says its enabled but /ranks is an unknown command.

### Describe the steps to reproduce the problem.
Well basically you set up your ranks and stuff ingame with /ranks and restart the server.

### Anything else we need to know?

Nope thats pretty much it the plugin is great besides ranks

**Comment by iiDirtblock** [comment]
i have the same problem too but mine never runs

**Comment by Hxtch2** [comment]
Yea this plugin would be so great and helpful if all this is fixed

**Comment by DylanFPS** [comment]
Closing because #81 provides more detail
