### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by CottonBawl** [MC-Prison/Prison#93]
Module: Mines

Can there please be a way to run a command through console that sets a players rank manually. I'll explain my reasoning. So in my "mines" There are 3. 2 of the mines are for everyone to use. But there will be 1 mine that only votes can get to. So in my SuperBvotes plugin, You can run commands through console when a player votes 5 times in a day. Ex: "pex user {user} timed add somecommand.somthingelse 84000" So the player will have to vote 5 times per day to access the mine because the "permission node" would be taken away once the 84000 seconds ran out. So I would use this command to temporarily set a players rank for a small time

**Comment by DylanFPS** [comment]
This seems unnecessary. You can control access to the mine through a warp plugin and that permission node, I see no reason why Prison, as bloated as it is, should need this. But will leave open anyway in case @faizaand has some comments
