### ISSUE TITLE
A Feature I Need

### ISSUE THREAD

**Issue by Jaffaaaa** [MC-Prison/Prison#98]
I'm happy to see the plugin work amazing so far with the ranks and the mines however I would like if I could set a mine to only work for people that are in a certain rank (or above).

**Comment by SevenSlayy** [comment]
This can easily be achieved by using a permissions manager and worldguard regions and only allowing those ranks in the region.

**Comment by Jaffaaaa** [comment]
I'm talking about the ranks from inside the prison plugin. Not pex etc

**Comment by SevenSlayy** [comment]
You can still use worldguard regions and just assign a group to those prison ranks using what I said.

**Comment by Jaffaaaa** [comment]
Any info on how I can do this?

**Comment by SevenSlayy** [comment]
https://github.com/MC-Prison/Prison/wiki/Ranks-Guidebook

**Comment by SevenSlayy** [comment]
Use a rank up command to do something like /pex user {player} group add RankName

**Comment by DylanFPS** [comment]
You need to use a permissions plugin with Ranks. Closing as a question. For future reference, if you want to ask a question or need support, do it in our Discord. Thanks :)
